var annotated_dup =
[
    [ "Modules", "d6/d44/md_docs_PROJECT_STRUCTURE.html#autotoc_md21", null ],
    [ "Nodes", "d6/d44/md_docs_PROJECT_STRUCTURE.html#autotoc_md22", null ],
    [ "Data Types", "d6/d44/md_docs_PROJECT_STRUCTURE.html#autotoc_md23", null ],
    [ "nitro", null, [
      [ "Im3D", null, [
        [ "Im3DModule", "d2/df1/classnitro_1_1Im3D_1_1Im3DModule.html", "d2/df1/classnitro_1_1Im3D_1_1Im3DModule" ]
      ] ],
      [ "ImCore", null, [
        [ "ImCoreModule", "db/d90/classnitro_1_1ImCore_1_1ImCoreModule.html", "db/d90/classnitro_1_1ImCore_1_1ImCoreModule" ]
      ] ],
      [ "ImExtra", null, [
        [ "ImExtraModule", "d4/d5f/classnitro_1_1ImExtra_1_1ImExtraModule.html", "d4/d5f/classnitro_1_1ImExtra_1_1ImExtraModule" ]
      ] ],
      [ "DraggableTreeWidget", "d5/d71/classnitro_1_1DraggableTreeWidget.html", "d5/d71/classnitro_1_1DraggableTreeWidget" ],
      [ "MainWindow", "dc/d7d/classnitro_1_1MainWindow.html", "dc/d7d/classnitro_1_1MainWindow" ],
      [ "ZoomBar", "dc/d18/classnitro_1_1ZoomBar.html", "dc/d18/classnitro_1_1ZoomBar" ],
      [ "NitroModule", "d7/d57/classnitro_1_1NitroModule.html", "d7/d57/classnitro_1_1NitroModule" ],
      [ "ColImageData", "d8/da4/classnitro_1_1ColImageData.html", "d8/da4/classnitro_1_1ColImageData" ],
      [ "DecimalData", "d9/dad/classnitro_1_1DecimalData.html", "d9/dad/classnitro_1_1DecimalData" ],
      [ "FlexibleData", "d8/dac/classnitro_1_1FlexibleData.html", "d8/dac/classnitro_1_1FlexibleData" ],
      [ "GrayImageData", "d1/dad/classnitro_1_1GrayImageData.html", "d1/dad/classnitro_1_1GrayImageData" ],
      [ "IntegerData", "d2/d9f/classnitro_1_1IntegerData.html", "d2/d9f/classnitro_1_1IntegerData" ],
      [ "NitroNode", "da/d5a/classnitro_1_1NitroNode.html", "da/d5a/classnitro_1_1NitroNode" ],
      [ "NitroNodeBuilder", "da/dd1/classnitro_1_1NitroNodeBuilder.html", "da/dd1/classnitro_1_1NitroNodeBuilder" ],
      [ "NodeOperator", "d0/d72/classnitro_1_1NodeOperator.html", "d0/d72/classnitro_1_1NodeOperator" ],
      [ "NodePorts", "da/da7/classnitro_1_1NodePorts.html", "da/da7/classnitro_1_1NodePorts" ],
      [ "NodeRegistry", "df/dd2/classnitro_1_1NodeRegistry.html", "df/dd2/classnitro_1_1NodeRegistry" ],
      [ "PortData", "d9/d6d/classnitro_1_1PortData.html", "d9/d6d/classnitro_1_1PortData" ],
      [ "ImageNodeGraphicsView", "d7/d22/classnitro_1_1ImageNodeGraphicsView.html", "d7/d22/classnitro_1_1ImageNodeGraphicsView" ],
      [ "NodeDockWidget", "de/db3/classnitro_1_1NodeDockWidget.html", "de/db3/classnitro_1_1NodeDockWidget" ],
      [ "StylePreset", "d9/d9e/structnitro_1_1StylePreset.html", "d9/d9e/structnitro_1_1StylePreset" ],
      [ "ImResourceReader", "d9/d52/classnitro_1_1ImResourceReader.html", null ],
      [ "RenderDockWidget", "d1/de0/classnitro_1_1RenderDockWidget.html", "d1/de0/classnitro_1_1RenderDockWidget" ],
      [ "Renderer", "d4/d51/classnitro_1_1Renderer.html", "d4/d51/classnitro_1_1Renderer" ],
      [ "ShaderRenderer", "d7/d1d/classnitro_1_1ShaderRenderer.html", "d7/d1d/classnitro_1_1ShaderRenderer" ],
      [ "RenderView", "db/d5a/classnitro_1_1RenderView.html", "db/d5a/classnitro_1_1RenderView" ],
      [ "Settings", "d1/d8a/structnitro_1_1Settings.html", "d1/d8a/structnitro_1_1Settings" ],
      [ "LayerRemovalOperator", "d6/d67/classnitro_1_1LayerRemovalOperator.html", "d6/d67/classnitro_1_1LayerRemovalOperator" ],
      [ "SurfaceViewOperator", "d0/d69/classnitro_1_1SurfaceViewOperator.html", "d0/d69/classnitro_1_1SurfaceViewOperator" ],
      [ "ResampleOperator", "d0/dfb/classnitro_1_1ResampleOperator.html", "d0/dfb/classnitro_1_1ResampleOperator" ],
      [ "CubicSampler", "d0/d0f/classnitro_1_1CubicSampler.html", "d0/d0f/classnitro_1_1CubicSampler" ],
      [ "Sampler", "d2/d6a/classnitro_1_1Sampler.html", "d2/d6a/classnitro_1_1Sampler" ],
      [ "ImViewDockWidget", "d4/dba/classnitro_1_1ImViewDockWidget.html", "d4/dba/classnitro_1_1ImViewDockWidget" ],
      [ "ImageInfo", "dc/de4/structnitro_1_1ImageInfo.html", "dc/de4/structnitro_1_1ImageInfo" ],
      [ "ImageViewer", "da/dea/classnitro_1_1ImageViewer.html", "da/dea/classnitro_1_1ImageViewer" ],
      [ "ColorMapOperator", "d5/d4a/classnitro_1_1ColorMapOperator.html", "d5/d4a/classnitro_1_1ColorMapOperator" ],
      [ "ConvertOperator", "da/d3b/classnitro_1_1ConvertOperator.html", "da/d3b/classnitro_1_1ConvertOperator" ],
      [ "MixOperator", "da/d0a/classnitro_1_1MixOperator.html", "da/d0a/classnitro_1_1MixOperator" ],
      [ "KMeansOperator", "d9/d71/classnitro_1_1KMeansOperator.html", "d9/d71/classnitro_1_1KMeansOperator" ],
      [ "QuantizeOperator", "d9/df2/classnitro_1_1QuantizeOperator.html", "d9/df2/classnitro_1_1QuantizeOperator" ],
      [ "BooleanMathOperator", "d5/d10/classnitro_1_1BooleanMathOperator.html", "d5/d10/classnitro_1_1BooleanMathOperator" ],
      [ "CombineOperator", "d6/dae/classnitro_1_1CombineOperator.html", "d6/dae/classnitro_1_1CombineOperator" ],
      [ "ImInfoOperator", "d5/d72/classnitro_1_1ImInfoOperator.html", "d5/d72/classnitro_1_1ImInfoOperator" ],
      [ "MathOperator", "d5/d7e/classnitro_1_1MathOperator.html", "d5/d7e/classnitro_1_1MathOperator" ],
      [ "InvertOperator", "dc/da1/classnitro_1_1InvertOperator.html", "dc/da1/classnitro_1_1InvertOperator" ],
      [ "NormalizeOperator", "d3/d08/classnitro_1_1NormalizeOperator.html", "d3/d08/classnitro_1_1NormalizeOperator" ],
      [ "ReductionOperator", "d9/d9d/classnitro_1_1ReductionOperator.html", "d9/d9d/classnitro_1_1ReductionOperator" ],
      [ "RgbToGrayscaleOperator", "df/d70/classnitro_1_1RgbToGrayscaleOperator.html", "df/d70/classnitro_1_1RgbToGrayscaleOperator" ],
      [ "SeparateOperator", "da/d88/classnitro_1_1SeparateOperator.html", "da/d88/classnitro_1_1SeparateOperator" ],
      [ "BilateralFilterOperator", "dc/d51/classnitro_1_1BilateralFilterOperator.html", "dc/d51/classnitro_1_1BilateralFilterOperator" ],
      [ "BoxFilterOperator", "d7/dd4/classnitro_1_1BoxFilterOperator.html", "d7/dd4/classnitro_1_1BoxFilterOperator" ],
      [ "GaussianBlurOperator", "da/da2/classnitro_1_1GaussianBlurOperator.html", "da/da2/classnitro_1_1GaussianBlurOperator" ],
      [ "ImageSourceOperator", "d0/db5/classnitro_1_1ImageSourceOperator.html", "d0/db5/classnitro_1_1ImageSourceOperator" ],
      [ "RandomOperator", "db/df7/classnitro_1_1RandomOperator.html", "db/df7/classnitro_1_1RandomOperator" ],
      [ "ImageViewOperator", "dd/d5e/classnitro_1_1ImageViewOperator.html", "dd/d5e/classnitro_1_1ImageViewOperator" ],
      [ "ValueViewOperator", "d4/d8b/classnitro_1_1ValueViewOperator.html", "d4/d8b/classnitro_1_1ValueViewOperator" ],
      [ "FlipOperator", "dd/dd4/classnitro_1_1FlipOperator.html", "dd/dd4/classnitro_1_1FlipOperator" ],
      [ "DenoiseOperator", "df/d2c/classnitro_1_1DenoiseOperator.html", "df/d2c/classnitro_1_1DenoiseOperator" ],
      [ "ImFlipOperator", "de/d2a/classnitro_1_1ImFlipOperator.html", "de/d2a/classnitro_1_1ImFlipOperator" ],
      [ "ResizeOperator", "d4/dd3/classnitro_1_1ResizeOperator.html", "d4/dd3/classnitro_1_1ResizeOperator" ],
      [ "ImRotateOperator", "d6/dbf/classnitro_1_1ImRotateOperator.html", "d6/dbf/classnitro_1_1ImRotateOperator" ],
      [ "TranslateOperator", "d4/dcd/classnitro_1_1TranslateOperator.html", "d4/dcd/classnitro_1_1TranslateOperator" ],
      [ "MatchSizeOperator", "db/ddd/classnitro_1_1MatchSizeOperator.html", "db/ddd/classnitro_1_1MatchSizeOperator" ],
      [ "DistanceTransformOperator", "d0/d04/classnitro_1_1DistanceTransformOperator.html", "d0/d04/classnitro_1_1DistanceTransformOperator" ],
      [ "CannyEdgeDetectionOperator", "d9/d11/classnitro_1_1CannyEdgeDetectionOperator.html", "d9/d11/classnitro_1_1CannyEdgeDetectionOperator" ],
      [ "DCTOperator", "d4/d49/classnitro_1_1DCTOperator.html", "d4/d49/classnitro_1_1DCTOperator" ],
      [ "FFTShiftOperator", "d0/dab/classnitro_1_1FFTShiftOperator.html", "d0/dab/classnitro_1_1FFTShiftOperator" ],
      [ "FFTOperator", "d7/dd3/classnitro_1_1FFTOperator.html", "d7/dd3/classnitro_1_1FFTOperator" ],
      [ "MorphologyOperator", "d7/d54/classnitro_1_1MorphologyOperator.html", "d7/d54/classnitro_1_1MorphologyOperator" ],
      [ "MaskOperator", "d9/da6/classnitro_1_1MaskOperator.html", "d9/da6/classnitro_1_1MaskOperator" ],
      [ "StructElemOperator", "dd/d91/classnitro_1_1StructElemOperator.html", "dd/d91/classnitro_1_1StructElemOperator" ],
      [ "ConnectedCompsOperator", "d8/d2f/classnitro_1_1ConnectedCompsOperator.html", "d8/d2f/classnitro_1_1ConnectedCompsOperator" ]
    ] ]
];