var annotated_dup =
[
    [ "Modules", "md_docs_PROJECT_STRUCTURE.html#autotoc_md21", null ],
    [ "Nodes", "md_docs_PROJECT_STRUCTURE.html#autotoc_md22", null ],
    [ "Data Types", "md_docs_PROJECT_STRUCTURE.html#autotoc_md23", null ],
    [ "nitro", null, [
      [ "Im3D", null, [
        [ "Im3DModule", "classnitro_1_1Im3D_1_1Im3DModule.html", "classnitro_1_1Im3D_1_1Im3DModule" ]
      ] ],
      [ "ImCore", null, [
        [ "ImCoreModule", "classnitro_1_1ImCore_1_1ImCoreModule.html", "classnitro_1_1ImCore_1_1ImCoreModule" ]
      ] ],
      [ "ImExtra", null, [
        [ "ImExtraModule", "classnitro_1_1ImExtra_1_1ImExtraModule.html", "classnitro_1_1ImExtra_1_1ImExtraModule" ]
      ] ],
      [ "DraggableTreeWidget", "classnitro_1_1DraggableTreeWidget.html", "classnitro_1_1DraggableTreeWidget" ],
      [ "MainWindow", "classnitro_1_1MainWindow.html", "classnitro_1_1MainWindow" ],
      [ "ZoomBar", "classnitro_1_1ZoomBar.html", "classnitro_1_1ZoomBar" ],
      [ "NitroModule", "classnitro_1_1NitroModule.html", "classnitro_1_1NitroModule" ],
      [ "DecimalData", "classnitro_1_1DecimalData.html", "classnitro_1_1DecimalData" ],
      [ "ImageData", "classnitro_1_1ImageData.html", "classnitro_1_1ImageData" ],
      [ "IntegerData", "classnitro_1_1IntegerData.html", "classnitro_1_1IntegerData" ],
      [ "NitroNode", "classnitro_1_1NitroNode.html", "classnitro_1_1NitroNode" ],
      [ "NitroNodeBuilder", "classnitro_1_1NitroNodeBuilder.html", "classnitro_1_1NitroNodeBuilder" ],
      [ "NodeOperator", "classnitro_1_1NodeOperator.html", "classnitro_1_1NodeOperator" ],
      [ "NodePorts", "classnitro_1_1NodePorts.html", "classnitro_1_1NodePorts" ],
      [ "NodeRegistry", "classnitro_1_1NodeRegistry.html", "classnitro_1_1NodeRegistry" ],
      [ "ImageNodeGraphicsView", "classnitro_1_1ImageNodeGraphicsView.html", "classnitro_1_1ImageNodeGraphicsView" ],
      [ "NodeDockWidget", "classnitro_1_1NodeDockWidget.html", "classnitro_1_1NodeDockWidget" ],
      [ "StylePreset", "structnitro_1_1StylePreset.html", "structnitro_1_1StylePreset" ],
      [ "ImResourceReader", "classnitro_1_1ImResourceReader.html", null ],
      [ "RenderDockWidget", "classnitro_1_1RenderDockWidget.html", "classnitro_1_1RenderDockWidget" ],
      [ "Renderer", "classnitro_1_1Renderer.html", "classnitro_1_1Renderer" ],
      [ "ShaderRenderer", "classnitro_1_1ShaderRenderer.html", "classnitro_1_1ShaderRenderer" ],
      [ "RenderView", "classnitro_1_1RenderView.html", "classnitro_1_1RenderView" ],
      [ "Settings", "structnitro_1_1Settings.html", "structnitro_1_1Settings" ],
      [ "LayerRemovalOperator", "classnitro_1_1LayerRemovalOperator.html", "classnitro_1_1LayerRemovalOperator" ],
      [ "ResampleOperator", "classnitro_1_1ResampleOperator.html", "classnitro_1_1ResampleOperator" ],
      [ "CubicSampler", "classnitro_1_1CubicSampler.html", "classnitro_1_1CubicSampler" ],
      [ "Sampler", "classnitro_1_1Sampler.html", "classnitro_1_1Sampler" ],
      [ "SurfaceViewAlgorithm", "classnitro_1_1SurfaceViewAlgorithm.html", "classnitro_1_1SurfaceViewAlgorithm" ],
      [ "ImViewDockWidget", "classnitro_1_1ImViewDockWidget.html", "classnitro_1_1ImViewDockWidget" ],
      [ "ImageViewer", "classnitro_1_1ImageViewer.html", "classnitro_1_1ImageViewer" ],
      [ "FlipOperator", "classnitro_1_1FlipOperator.html", "classnitro_1_1FlipOperator" ],
      [ "CombineOperator", "classnitro_1_1CombineOperator.html", "classnitro_1_1CombineOperator" ],
      [ "ConvertOperator", "classnitro_1_1ConvertOperator.html", "classnitro_1_1ConvertOperator" ],
      [ "GrayscaleConvertOperator", "classnitro_1_1GrayscaleConvertOperator.html", "classnitro_1_1GrayscaleConvertOperator" ],
      [ "MathOperator", "classnitro_1_1MathOperator.html", "classnitro_1_1MathOperator" ],
      [ "MixOperator", "classnitro_1_1MixOperator.html", "classnitro_1_1MixOperator" ],
      [ "SeparateOperator", "classnitro_1_1SeparateOperator.html", "classnitro_1_1SeparateOperator" ],
      [ "BilateralFilterOperator", "classnitro_1_1BilateralFilterOperator.html", "classnitro_1_1BilateralFilterOperator" ],
      [ "BoxFilterOperator", "classnitro_1_1BoxFilterOperator.html", "classnitro_1_1BoxFilterOperator" ],
      [ "DenoiseOperator", "classnitro_1_1DenoiseOperator.html", "classnitro_1_1DenoiseOperator" ],
      [ "GaussianBlurOperator", "classnitro_1_1GaussianBlurOperator.html", "classnitro_1_1GaussianBlurOperator" ],
      [ "ThresholdOperator", "classnitro_1_1ThresholdOperator.html", "classnitro_1_1ThresholdOperator" ],
      [ "ImageViewAlgorithm", "classnitro_1_1ImageViewAlgorithm.html", "classnitro_1_1ImageViewAlgorithm" ],
      [ "KMeansOperator", "classnitro_1_1KMeansOperator.html", "classnitro_1_1KMeansOperator" ],
      [ "QuantizeOperator", "classnitro_1_1QuantizeOperator.html", "classnitro_1_1QuantizeOperator" ],
      [ "ImFlipOperator", "classnitro_1_1ImFlipOperator.html", "classnitro_1_1ImFlipOperator" ],
      [ "ResizeOperator", "classnitro_1_1ResizeOperator.html", "classnitro_1_1ResizeOperator" ],
      [ "ImRotateOperator", "classnitro_1_1ImRotateOperator.html", "classnitro_1_1ImRotateOperator" ],
      [ "ColorMapOperator", "classnitro_1_1ColorMapOperator.html", "classnitro_1_1ColorMapOperator" ],
      [ "ImInfoOperator", "classnitro_1_1ImInfoOperator.html", "classnitro_1_1ImInfoOperator" ],
      [ "InvertOperator", "classnitro_1_1InvertOperator.html", "classnitro_1_1InvertOperator" ],
      [ "NormalizeOperator", "classnitro_1_1NormalizeOperator.html", "classnitro_1_1NormalizeOperator" ],
      [ "CannyEdgeDetectionOperator", "classnitro_1_1CannyEdgeDetectionOperator.html", "classnitro_1_1CannyEdgeDetectionOperator" ],
      [ "FFTShift", "classnitro_1_1FFTShift.html", "classnitro_1_1FFTShift" ],
      [ "FFTOperator", "classnitro_1_1FFTOperator.html", "classnitro_1_1FFTOperator" ],
      [ "MaskOperator", "classnitro_1_1MaskOperator.html", "classnitro_1_1MaskOperator" ],
      [ "StructElemOperator", "classnitro_1_1StructElemOperator.html", "classnitro_1_1StructElemOperator" ],
      [ "MorphologyOperator", "classnitro_1_1MorphologyOperator.html", "classnitro_1_1MorphologyOperator" ]
    ] ]
];