var annotated_dup =
[
    [ "Modules", "d6/d44/md_docs_PROJECT_STRUCTURE.html#autotoc_md21", null ],
    [ "Nodes", "d6/d44/md_docs_PROJECT_STRUCTURE.html#autotoc_md22", null ],
    [ "Data Types", "d6/d44/md_docs_PROJECT_STRUCTURE.html#autotoc_md23", null ],
    [ "nitro", null, [
      [ "Compression", null, [
        [ "Compression", "de/d15/classnitro_1_1Compression_1_1Compression.html", "de/d15/classnitro_1_1Compression_1_1Compression" ],
        [ "JpegOperator", "d8/dac/classnitro_1_1Compression_1_1JpegOperator.html", "d8/dac/classnitro_1_1Compression_1_1JpegOperator" ],
        [ "PngOperator", "d1/d9d/classnitro_1_1Compression_1_1PngOperator.html", "d1/d9d/classnitro_1_1Compression_1_1PngOperator" ],
        [ "ZLibOperator", "d5/d34/classnitro_1_1Compression_1_1ZLibOperator.html", "d5/d34/classnitro_1_1Compression_1_1ZLibOperator" ]
      ] ],
      [ "ImCore", null, [
        [ "ImCore", "d0/dc2/classnitro_1_1ImCore_1_1ImCore.html", "d0/dc2/classnitro_1_1ImCore_1_1ImCore" ],
        [ "HistogramViewerDockWidget", "d7/dc4/classnitro_1_1ImCore_1_1HistogramViewerDockWidget.html", "d7/dc4/classnitro_1_1ImCore_1_1HistogramViewerDockWidget" ],
        [ "HistogramView", "d2/d2a/classnitro_1_1ImCore_1_1HistogramView.html", "d2/d2a/classnitro_1_1ImCore_1_1HistogramView" ],
        [ "ImageViewer", "df/dc9/classnitro_1_1ImCore_1_1ImageViewer.html", "df/dc9/classnitro_1_1ImCore_1_1ImageViewer" ],
        [ "ImViewDockWidget", "d8/d91/classnitro_1_1ImCore_1_1ImViewDockWidget.html", "d8/d91/classnitro_1_1ImCore_1_1ImViewDockWidget" ],
        [ "ColorMapOperator", "d1/d27/classnitro_1_1ImCore_1_1ColorMapOperator.html", "d1/d27/classnitro_1_1ImCore_1_1ColorMapOperator" ],
        [ "ConvertOperator", "dc/d0d/classnitro_1_1ImCore_1_1ConvertOperator.html", "dc/d0d/classnitro_1_1ImCore_1_1ConvertOperator" ],
        [ "MixOperator", "da/d62/classnitro_1_1ImCore_1_1MixOperator.html", "da/d62/classnitro_1_1ImCore_1_1MixOperator" ],
        [ "UniformConvertOperator", "d3/d22/classnitro_1_1ImCore_1_1UniformConvertOperator.html", "d3/d22/classnitro_1_1ImCore_1_1UniformConvertOperator" ],
        [ "BooleanMathOperator", "de/d8f/classnitro_1_1ImCore_1_1BooleanMathOperator.html", "de/d8f/classnitro_1_1ImCore_1_1BooleanMathOperator" ],
        [ "CombineOperator", "d3/d8b/classnitro_1_1ImCore_1_1CombineOperator.html", "d3/d8b/classnitro_1_1ImCore_1_1CombineOperator" ],
        [ "ImInfoOperator", "d0/d38/classnitro_1_1ImCore_1_1ImInfoOperator.html", "d0/d38/classnitro_1_1ImCore_1_1ImInfoOperator" ],
        [ "MathOperator", "dc/d7a/classnitro_1_1ImCore_1_1MathOperator.html", "dc/d7a/classnitro_1_1ImCore_1_1MathOperator" ],
        [ "InvertOperator", "d4/d5f/classnitro_1_1ImCore_1_1InvertOperator.html", "d4/d5f/classnitro_1_1ImCore_1_1InvertOperator" ],
        [ "MapRangeOperator", "d0/d5c/classnitro_1_1ImCore_1_1MapRangeOperator.html", "d0/d5c/classnitro_1_1ImCore_1_1MapRangeOperator" ],
        [ "NormalizeOperator", "d3/d0a/classnitro_1_1ImCore_1_1NormalizeOperator.html", "d3/d0a/classnitro_1_1ImCore_1_1NormalizeOperator" ],
        [ "ReductionOperator", "d6/d40/classnitro_1_1ImCore_1_1ReductionOperator.html", "d6/d40/classnitro_1_1ImCore_1_1ReductionOperator" ],
        [ "RgbToGrayscaleOperator", "d2/d0b/classnitro_1_1ImCore_1_1RgbToGrayscaleOperator.html", "d2/d0b/classnitro_1_1ImCore_1_1RgbToGrayscaleOperator" ],
        [ "SeparateOperator", "de/d36/classnitro_1_1ImCore_1_1SeparateOperator.html", "de/d36/classnitro_1_1ImCore_1_1SeparateOperator" ],
        [ "ImageSourceOperator", "d2/de4/classnitro_1_1ImCore_1_1ImageSourceOperator.html", "d2/de4/classnitro_1_1ImCore_1_1ImageSourceOperator" ],
        [ "RandomOperator", "db/d97/classnitro_1_1ImCore_1_1RandomOperator.html", "db/d97/classnitro_1_1ImCore_1_1RandomOperator" ],
        [ "RgbOperator", "de/df3/classnitro_1_1ImCore_1_1RgbOperator.html", "de/df3/classnitro_1_1ImCore_1_1RgbOperator" ],
        [ "HistogramViewOperator", "d0/df1/classnitro_1_1ImCore_1_1HistogramViewOperator.html", "d0/df1/classnitro_1_1ImCore_1_1HistogramViewOperator" ],
        [ "ImageViewOperator", "de/d69/classnitro_1_1ImCore_1_1ImageViewOperator.html", "de/d69/classnitro_1_1ImCore_1_1ImageViewOperator" ],
        [ "ValueViewOperator", "da/d00/classnitro_1_1ImCore_1_1ValueViewOperator.html", "da/d00/classnitro_1_1ImCore_1_1ValueViewOperator" ],
        [ "ImFlipOperator", "df/d20/classnitro_1_1ImCore_1_1ImFlipOperator.html", "df/d20/classnitro_1_1ImCore_1_1ImFlipOperator" ],
        [ "ResizeOperator", "d2/d43/classnitro_1_1ImCore_1_1ResizeOperator.html", "d2/d43/classnitro_1_1ImCore_1_1ResizeOperator" ],
        [ "ImRotateOperator", "db/d33/classnitro_1_1ImCore_1_1ImRotateOperator.html", "db/d33/classnitro_1_1ImCore_1_1ImRotateOperator" ],
        [ "TranslateOperator", "d8/dc4/classnitro_1_1ImCore_1_1TranslateOperator.html", "d8/dc4/classnitro_1_1ImCore_1_1TranslateOperator" ],
        [ "MatchSizeOperator", "d0/d65/classnitro_1_1ImCore_1_1MatchSizeOperator.html", "d0/d65/classnitro_1_1ImCore_1_1MatchSizeOperator" ]
      ] ],
      [ "ImProc", null, [
        [ "ImProc", "d9/d64/classnitro_1_1ImProc_1_1ImProc.html", "d9/d64/classnitro_1_1ImProc_1_1ImProc" ],
        [ "DistanceTransformOperator", "da/da3/classnitro_1_1ImProc_1_1DistanceTransformOperator.html", "da/da3/classnitro_1_1ImProc_1_1DistanceTransformOperator" ],
        [ "BilateralFilterOperator", "de/d6d/classnitro_1_1ImProc_1_1BilateralFilterOperator.html", "de/d6d/classnitro_1_1ImProc_1_1BilateralFilterOperator" ],
        [ "BoxFilterOperator", "d9/d42/classnitro_1_1ImProc_1_1BoxFilterOperator.html", "d9/d42/classnitro_1_1ImProc_1_1BoxFilterOperator" ],
        [ "GaussianBlurOperator", "d2/da6/classnitro_1_1ImProc_1_1GaussianBlurOperator.html", "d2/da6/classnitro_1_1ImProc_1_1GaussianBlurOperator" ],
        [ "CannyEdgeDetectionOperator", "d0/d3c/classnitro_1_1ImProc_1_1CannyEdgeDetectionOperator.html", "d0/d3c/classnitro_1_1ImProc_1_1CannyEdgeDetectionOperator" ],
        [ "DCTOperator", "da/d45/classnitro_1_1ImProc_1_1DCTOperator.html", "da/d45/classnitro_1_1ImProc_1_1DCTOperator" ],
        [ "FFTShiftOperator", "d6/d26/classnitro_1_1ImProc_1_1FFTShiftOperator.html", "d6/d26/classnitro_1_1ImProc_1_1FFTShiftOperator" ],
        [ "FFTOperator", "d1/db6/classnitro_1_1ImProc_1_1FFTOperator.html", "d1/db6/classnitro_1_1ImProc_1_1FFTOperator" ],
        [ "MorphologyOperator", "d4/dd6/classnitro_1_1ImProc_1_1MorphologyOperator.html", "d4/dd6/classnitro_1_1ImProc_1_1MorphologyOperator" ],
        [ "MaskOperator", "df/d14/classnitro_1_1ImProc_1_1MaskOperator.html", "df/d14/classnitro_1_1ImProc_1_1MaskOperator" ],
        [ "StructElemOperator", "da/d15/classnitro_1_1ImProc_1_1StructElemOperator.html", "da/d15/classnitro_1_1ImProc_1_1StructElemOperator" ],
        [ "FlipOperator", "de/ded/classnitro_1_1ImProc_1_1FlipOperator.html", "de/ded/classnitro_1_1ImProc_1_1FlipOperator" ],
        [ "MseOperator", "d7/dab/classnitro_1_1ImProc_1_1MseOperator.html", "d7/dab/classnitro_1_1ImProc_1_1MseOperator" ],
        [ "PsnrOperator", "de/daf/classnitro_1_1ImProc_1_1PsnrOperator.html", "de/daf/classnitro_1_1ImProc_1_1PsnrOperator" ],
        [ "KMeansOperator", "da/d86/classnitro_1_1ImProc_1_1KMeansOperator.html", "da/d86/classnitro_1_1ImProc_1_1KMeansOperator" ],
        [ "QuantizeOperator", "de/d33/classnitro_1_1ImProc_1_1QuantizeOperator.html", "de/d33/classnitro_1_1ImProc_1_1QuantizeOperator" ],
        [ "DenoiseOperator", "dc/d48/classnitro_1_1ImProc_1_1DenoiseOperator.html", "dc/d48/classnitro_1_1ImProc_1_1DenoiseOperator" ],
        [ "ConnectedCompsOperator", "d3/d5c/classnitro_1_1ImProc_1_1ConnectedCompsOperator.html", "d3/d5c/classnitro_1_1ImProc_1_1ConnectedCompsOperator" ]
      ] ],
      [ "Thesis", null, [
        [ "Thesis", "d9/dba/classnitro_1_1Thesis_1_1Thesis.html", "d9/dba/classnitro_1_1Thesis_1_1Thesis" ],
        [ "RenderDockWidget", "d7/d2b/classnitro_1_1Thesis_1_1RenderDockWidget.html", "d7/d2b/classnitro_1_1Thesis_1_1RenderDockWidget" ],
        [ "Renderer", "d8/d7c/classnitro_1_1Thesis_1_1Renderer.html", "d8/d7c/classnitro_1_1Thesis_1_1Renderer" ],
        [ "ShaderRenderer", "d6/d2a/classnitro_1_1Thesis_1_1ShaderRenderer.html", "d6/d2a/classnitro_1_1Thesis_1_1ShaderRenderer" ],
        [ "RenderView", "d6/d1e/classnitro_1_1Thesis_1_1RenderView.html", "d6/d1e/classnitro_1_1Thesis_1_1RenderView" ],
        [ "CompressOperator", "d8/d78/classnitro_1_1Thesis_1_1CompressOperator.html", "d8/d78/classnitro_1_1Thesis_1_1CompressOperator" ],
        [ "DecompressOperator", "d8/d84/classnitro_1_1Thesis_1_1DecompressOperator.html", "d8/d84/classnitro_1_1Thesis_1_1DecompressOperator" ],
        [ "LayerRemovalOperator", "dd/d58/classnitro_1_1Thesis_1_1LayerRemovalOperator.html", "dd/d58/classnitro_1_1Thesis_1_1LayerRemovalOperator" ],
        [ "SurfaceViewOperator", "da/d56/classnitro_1_1Thesis_1_1SurfaceViewOperator.html", "da/d56/classnitro_1_1Thesis_1_1SurfaceViewOperator" ],
        [ "ResampleOperator", "d0/dfa/classnitro_1_1Thesis_1_1ResampleOperator.html", "d0/dfa/classnitro_1_1Thesis_1_1ResampleOperator" ]
      ] ],
      [ "MainWindow", "dc/d7d/classnitro_1_1MainWindow.html", "dc/d7d/classnitro_1_1MainWindow" ],
      [ "NitroDockWidget", "de/df7/classnitro_1_1NitroDockWidget.html", "de/df7/classnitro_1_1NitroDockWidget" ],
      [ "ZoomBar", "dc/d18/classnitro_1_1ZoomBar.html", "dc/d18/classnitro_1_1ZoomBar" ],
      [ "NitroModule", "d7/d57/classnitro_1_1NitroModule.html", "d7/d57/classnitro_1_1NitroModule" ],
      [ "DecimalData", "d9/dad/classnitro_1_1DecimalData.html", "d9/dad/classnitro_1_1DecimalData" ],
      [ "FlexibleData", "d8/dac/classnitro_1_1FlexibleData.html", "d8/dac/classnitro_1_1FlexibleData" ],
      [ "IntegerData", "d2/d9f/classnitro_1_1IntegerData.html", "d2/d9f/classnitro_1_1IntegerData" ],
      [ "NitroNode", "da/d5a/classnitro_1_1NitroNode.html", "da/d5a/classnitro_1_1NitroNode" ],
      [ "NitroNodeBuilder", "da/dd1/classnitro_1_1NitroNodeBuilder.html", "da/dd1/classnitro_1_1NitroNodeBuilder" ],
      [ "NodeOperator", "d0/d72/classnitro_1_1NodeOperator.html", "d0/d72/classnitro_1_1NodeOperator" ],
      [ "NodePorts", "da/da7/classnitro_1_1NodePorts.html", "da/da7/classnitro_1_1NodePorts" ],
      [ "NodeRegistry", "df/dd2/classnitro_1_1NodeRegistry.html", "df/dd2/classnitro_1_1NodeRegistry" ],
      [ "PortData", "d9/d6d/classnitro_1_1PortData.html", "d9/d6d/classnitro_1_1PortData" ],
      [ "DraggableTreeWidget", "d5/d71/classnitro_1_1DraggableTreeWidget.html", "d5/d71/classnitro_1_1DraggableTreeWidget" ],
      [ "ImageNodeGraphicsView", "d7/d22/classnitro_1_1ImageNodeGraphicsView.html", "d7/d22/classnitro_1_1ImageNodeGraphicsView" ],
      [ "NodeDockWidget", "de/db3/classnitro_1_1NodeDockWidget.html", "de/db3/classnitro_1_1NodeDockWidget" ],
      [ "ImResourceReader", "d9/d52/classnitro_1_1ImResourceReader.html", "d9/d52/classnitro_1_1ImResourceReader" ],
      [ "ColImageData", "d8/da4/classnitro_1_1ColImageData.html", "d8/da4/classnitro_1_1ColImageData" ],
      [ "GrayImageData", "d1/dad/classnitro_1_1GrayImageData.html", "d1/dad/classnitro_1_1GrayImageData" ]
    ] ]
];